[hooks]
pre-commit = """
	echo hooks: running rustfmt... && \
	cargo +nightly fmt && \
	git add $(git diff --name-only --cached --diff-filter=ACM) && \
	echo hooks: running clippy... && \
	cargo clippy --fix --allow-staged && \
	git add $(git diff --name-only --cached --diff-filter=ACM)\
	"""

[logging]
verbose = false
