name: Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tarpaulin:
    name: Run tests with Tarpaulin
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin
      options: --security-opt seccomp=unconfined
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up environment cache
        uses: Swatinem/rust-cache@v2
      - name: Setup Consul Agent for tests
        run: |
          curl -L -o /tmp/consul.zip https://releases.hashicorp.com/consul/1.12.3/consul_1.12.3_linux_amd64.zip
          unzip /tmp/consul.zip
          ./consul agent -dev -client 0.0.0.0 -hcl 'acl = { enabled = true default_policy = "allow" enable_token_persistence = true }' > /tmp/consul.log &
      - name: Generate code coverage
        run: |
          cargo tarpaulin --verbose --all-features --workspace --timeout 120 --out Xml -- --test-threads=1
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
